Update .github/workflows/android.yml
If the Boost on Bintray is not available for download, use the Wayback Machine instead (if available).

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -54,6 +54,19 @@ jobs:
       run: |
         . envsetup.sh
         cd packaging/android
+        declare BOOST_VERSION="$(grep -- '--boost=' androidbuild.sh | awk '{print $1}' | sed -e 's/--boost=//')"
+        if [ ! "x$(command -v wget)X" == "xX" ]; then
+          declare BINTRAY_BOOST_HTTP_STATUS="$(wget --spider --quiet -S "http://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_$(echo "${BOOST_VERSION}" | sed -e 's/\./_/g').tar.bz2" 2>&1 | grep "HTTP/" | awk '{print $2}')"
+        elif [ ! "x$(command -v curl)X" == "xX" ]; then
+          declare BINTRAY_BOOST_HTTP_STATUS="$(curl -o /dev/null --silent --head --write-out '%{http_code}' "http://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_$(echo "${BOOST_VERSION}" | sed -e 's/\./_/g').tar.bz2")"
+        else
+          echo -e "\e[1;31m<Error>\e[m Wget and cURL are not found"
+          exit 1
+        fi
+        if [ "x${BINTRAY_BOOST_HTTP_STATUS:0:1}X" == "x4X" -o "x${BINTRAY_BOOST_HTTP_STATUS:0:1}X" == "x5X" ]; then
+          echo -e "\e[1;33m<Warning>\e[m Boost on Bintray is currently not available for download, so use the Wayback Machine instead (if available)."
+          sed -i -e '/git clone https:\/\/github\.com\/moritz-wundke\/Boost-for-Android \$DOWNLOADS_DIR\/boost$/a\         sed -i -e '"'"'s#BOOST_DOWNLOAD_LINK="http://dl.bintray.com/boostorg/release#BOOST_DOWNLOAD_LINK="http://web.archive.org/web/0/http://dl.bintray.com/boostorg/release#'"'"' $DOWNLOADS_DIR/boost/build-android.sh' androidbuild.sh
+        fi
         ./androidbuild.sh\
          -p=all\
          --src="${KRITA_SRC}"\
@@ -176,6 +189,19 @@ jobs:
       run: |
         . envsetup.sh
         cd packaging/android
+        declare BOOST_VERSION="$(grep -- '--boost=' androidbuild.sh | awk '{print $1}' | sed -e 's/--boost=//')"
+        if [ ! "x$(command -v wget)X" == "xX" ]; then
+          declare BINTRAY_BOOST_HTTP_STATUS="$(wget --spider --quiet -S "http://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_$(echo "${BOOST_VERSION}" | sed -e 's/\./_/g').tar.bz2" 2>&1 | grep "HTTP/" | awk '{print $2}')"
+        elif [ ! "x$(command -v curl)X" == "xX" ]; then
+          declare BINTRAY_BOOST_HTTP_STATUS="$(curl -o /dev/null --silent --head --write-out '%{http_code}' "http://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_$(echo "${BOOST_VERSION}" | sed -e 's/\./_/g').tar.bz2")"
+        else
+          echo -e "\e[1;31m<Error>\e[m Wget and cURL are not found"
+          exit 1
+        fi
+        if [ "x${BINTRAY_BOOST_HTTP_STATUS:0:1}X" == "x4X" -o "x${BINTRAY_BOOST_HTTP_STATUS:0:1}X" == "x5X" ]; then
+          echo -e "\e[1;33m<Warning>\e[m Boost on Bintray is currently not available for download, so use the Wayback Machine instead (if available)."
+          sed -i -e '/git clone https:\/\/github\.com\/moritz-wundke\/Boost-for-Android \$DOWNLOADS_DIR\/boost$/a\         sed -i -e '"'"'s#BOOST_DOWNLOAD_LINK="http://dl.bintray.com/boostorg/release#BOOST_DOWNLOAD_LINK="http://web.archive.org/web/0/http://dl.bintray.com/boostorg/release#'"'"' $DOWNLOADS_DIR/boost/build-android.sh' androidbuild.sh
+        fi
         ./androidbuild.sh\
          -p=all\
          --src="${KRITA_SRC}"\
@@ -298,6 +324,19 @@ jobs:
       run: |
         . envsetup.sh
         cd packaging/android
+        declare BOOST_VERSION="$(grep -- '--boost=' androidbuild.sh | awk '{print $1}' | sed -e 's/--boost=//')"
+        if [ ! "x$(command -v wget)X" == "xX" ]; then
+          declare BINTRAY_BOOST_HTTP_STATUS="$(wget --spider --quiet -S "http://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_$(echo "${BOOST_VERSION}" | sed -e 's/\./_/g').tar.bz2" 2>&1 | grep "HTTP/" | awk '{print $2}')"
+        elif [ ! "x$(command -v curl)X" == "xX" ]; then
+          declare BINTRAY_BOOST_HTTP_STATUS="$(curl -o /dev/null --silent --head --write-out '%{http_code}' "http://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_$(echo "${BOOST_VERSION}" | sed -e 's/\./_/g').tar.bz2")"
+        else
+          echo -e "\e[1;31m<Error>\e[m Wget and cURL are not found"
+          exit 1
+        fi
+        if [ "x${BINTRAY_BOOST_HTTP_STATUS:0:1}X" == "x4X" -o "x${BINTRAY_BOOST_HTTP_STATUS:0:1}X" == "x5X" ]; then
+          echo -e "\e[1;33m<Warning>\e[m Boost on Bintray is currently not available for download, so use the Wayback Machine instead (if available)."
+          sed -i -e '/git clone https:\/\/github\.com\/moritz-wundke\/Boost-for-Android \$DOWNLOADS_DIR\/boost$/a\         sed -i -e '"'"'s#BOOST_DOWNLOAD_LINK="http://dl.bintray.com/boostorg/release#BOOST_DOWNLOAD_LINK="http://web.archive.org/web/0/http://dl.bintray.com/boostorg/release#'"'"' $DOWNLOADS_DIR/boost/build-android.sh' androidbuild.sh
+        fi
         ./androidbuild.sh\
          -p=all\
          --src="${KRITA_SRC}"\
@@ -420,6 +459,19 @@ jobs:
       run: |
         . envsetup.sh
         cd packaging/android
+        declare BOOST_VERSION="$(grep -- '--boost=' androidbuild.sh | awk '{print $1}' | sed -e 's/--boost=//')"
+        if [ ! "x$(command -v wget)X" == "xX" ]; then
+          declare BINTRAY_BOOST_HTTP_STATUS="$(wget --spider --quiet -S "http://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_$(echo "${BOOST_VERSION}" | sed -e 's/\./_/g').tar.bz2" 2>&1 | grep "HTTP/" | awk '{print $2}')"
+        elif [ ! "x$(command -v curl)X" == "xX" ]; then
+          declare BINTRAY_BOOST_HTTP_STATUS="$(curl -o /dev/null --silent --head --write-out '%{http_code}' "http://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_$(echo "${BOOST_VERSION}" | sed -e 's/\./_/g').tar.bz2")"
+        else
+          echo -e "\e[1;31m<Error>\e[m Wget and cURL are not found"
+          exit 1
+        fi
+        if [ "x${BINTRAY_BOOST_HTTP_STATUS:0:1}X" == "x4X" -o "x${BINTRAY_BOOST_HTTP_STATUS:0:1}X" == "x5X" ]; then
+          echo -e "\e[1;33m<Warning>\e[m Boost on Bintray is currently not available for download, so use the Wayback Machine instead (if available)."
+          sed -i -e '/git clone https:\/\/github\.com\/moritz-wundke\/Boost-for-Android \$DOWNLOADS_DIR\/boost$/a\         sed -i -e '"'"'s#BOOST_DOWNLOAD_LINK="http://dl.bintray.com/boostorg/release#BOOST_DOWNLOAD_LINK="http://web.archive.org/web/0/http://dl.bintray.com/boostorg/release#'"'"' $DOWNLOADS_DIR/boost/build-android.sh' androidbuild.sh
+        fi
         ./androidbuild.sh\
          -p=all\
          --src="${KRITA_SRC}"\
